py_binary(
    name = "server",
    srcs = [
        "server.py",
    ],
    srcs_version = "PY2AND3",
    deps = [
        "@com_github_google_python_gflags//:gflags",
        "@org_pocoo_werkzeug//:werkzeug",
    ],
)
